# Generated by Django 5.0.1 on 2024-06-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attempt',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of Attempts'),
        ),
    ]
